export const NETWORK_LOGIN_SUCCESS = 'user/NETWORK_LOGIN_SUCCESS';
export const NETWORK_LOGIN_ERROR = 'user/NETWORK_LOGIN_ERROR';
export const NETWORK_LOGIN_PENDING = 'user/NETWORK_LOGIN_PENDING';

export const NETWORK_LOGOUT_SUCCESS = 'user/NETWORK_LOGOUT_SUCCESS';
export const NETWORK_LOGOUT_ERROR = 'user/NETWORK_LOGOUT_ERROR';
export const NETWORK_LOGOUT_PENDING = 'user/NETWORK_LOGOUT_PENDING';

export const FETCH_AUTHSTATUS_SUCCESS = 'user/FETCH_AUTHSTATUS_SUCCESS';
export const FETCH_AUTHSTATUS_ERROR = 'user/FETCH_AUTHSTATUS_ERROR';
export const FETCH_AUTHSTATUS_PENDING = 'user/FETCH_AUTHSTATUS_PENDING';

export const LOCAL_LOGOUT = 'user/LOCAL_LOGOUT';
export const SET_CURRENT_USER = 'user/SET_CURRENT_USER';
